version: '3.8'

services:
  # Airflow 웹서버
  airflow-webserver:
    image: apache/airflow:2.8.0-python3.13
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./resources:/opt/airflow/resources
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  # Airflow 스케줄러
  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.13
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./resources:/opt/airflow/resources
      - ./data:/opt/airflow/data
    command: scheduler
